export const BOOKING_STATUS = {
    PENDING: 'PENDING',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    EXPIRED: 'EXPIRED',
    TICKET_GENERATED: 'TICKET_GENERATED',
    CHECKED_IN: 'CHECKED_IN',
};

export const ENTRY_ACTION = {
    ENTRY: 'ENTRY',
    RE_ENTRY: 'RE_ENTRY',
};

export const MAX_TICKETS_PER_USER = 5;
export const TOTAL_EVENT_CAPACITY = 350;

export const RESERVATION_TIME = 10 * 60 * 1000; // 10 minutes
